---
name: Automatic Tag-release

on:  # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  automatic-tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
